---
- name: Restrict exposing kernel addresses (kptr_restrict)
  sysctl:
    name: kernel.kptr_restrict
    value: 2
    sysctl_set: yes

- name: Disable Linux Magic System Request (sysrq)
  sysctl:
    name: kernel.sysrq
    value: 0
    sysctl_set: yes

- name: Disabe IPv4 redirection acceptance (all.accept_redirects)
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    sysctl_set: yes

- name: Disabe IPv4 redirection acceptance (default.accept_redirects)
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: 0
    sysctl_set: yes

- name: Enable logging of Martian packets (all.log_martians)
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    sysctl_set: yes

- name: Enable logging of Martian packets (default.log_martians)
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: 1
    sysctl_set: yes

- name: Disabe sending of IPv4 redirects (send_redirects)
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    sysctl_set: yes

- name: Disabe IPv6 redirection acceptance (all.accept_redirects)
  sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: 0
    sysctl_set: yes

- name: Disabe IPv6 redirection acceptance (default.accept_redirects)
  sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: 0
    sysctl_set: yes
