---
- name: Install Extra Packages for Enterprise Linux (EPEL) repo
  yum:
    name: epel-release
    state: installed

- include: aide.yml
  tags: aide

- include: arpwatch.yml
  tags: arpwatch

- include: bash.yml
  tags: bash

- include: bind-utils.yml
  tags: bind-utils

- include: fail2ban.yml
  tags: fail2ban

- include: git.yml
  tags: git

- include: man.yml
  tags: man

- include: ntp.yml
  tags: ntp

- include: rkhunter.yml
  tags: rkhunter

- include: vim.yml
  tags: vim

- include: wget.yml
  tags: wget

- include: yum.yml
  tags: yum
