---
- name: Install Extra Packages for Enterprise Linux (EPEL) repo
  yum:
    name: epel-release
    state: installed
  become: true

- include: aide.yml
  tags: aide

- include: arpwatch.yml
  tags: arpwatch

- include: bash.yml
  tags: bash

- include: bind-utils.yml
  tags: bind-utils

- include: csh.yml
  tags: csh

- include: dstat.yml
  tags: dstat

- include: fail2ban.yml
  tags: fail2ban

- include: filesystem.yml
  tags: filesystem

- include: git.yml
  tags: git

- include: hosts.yml
  tags: hosts

- include: htop.yml
  tags: htop

- include: iftop.yml
  tags: iftop

- include: iotop.yml
  tags: iotop

- include: kernel.yml
  tags: kernel

- include: login.yml
  tags: login

- include: mailx.yml
  tags: mailx

- include: man.yml
  tags: man

- include: modprobe.yml
  tags: modprobe

- include: mtr.yml
  tags: mtr

- include: ncdu.yml
  tags: ncdu

- include: net-tools.yml
  tags: net-tools

- include: ntp.yml
  tags: ntp

- include: open-vm-tools.yml
  tags: open-vm-tools

- include: rkhunter.yml
  tags: rkhunter

- include: screen.yml
  tags: screen

- include: strace.yml
  tags: strace

- include: traceroute.yml
  tags: traceroute

- include: vim.yml
  tags: vim

- include: wget.yml
  tags: wget

- include: yum-utils.yml
  tags: yum-utils